### ISSUE TITLE
Wrongly displayed characters.

### ISSUE THREAD

**Issue by Hoverbear** [jocafa/Bindle#1]
![Error](http://i.imgur.com/62sYn.png)

Is there some special settings to use?

**Comment by jocafa** [comment]
You need to install one of the patched fonts for use with the Powerline plugin for vim.  You can get one here: https://github.com/Lokaltog/vim-powerline/wiki/Patched-fonts   I think I'm using the patched version of Menlo.

As for other goodies, I got a lot of information from this article: http://www.drbunsen.org/text-triumvirate.html

Enjoy!
--Josh

**Comment by Hoverbear** [comment]
Works fantastic. Thanks.
Perhaps this should be in a readme.md
